# Generated by Django 6.0.3 on 2026-03-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_category_remove_projects_technologies_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
