# Generated by Django 6.0.3 on 2026-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_technology_icon_technology_slug_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(unique=True, null=True),
        ),
    ]
