# Generated by Django 6.0.3 on 2026-07-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_populate_technology_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/features/'),
        ),
        migrations.CreateModel(
            name='LessonLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='projects/architecture/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='portfolio.project')),
            ],
        ),
    ]
