# Generated by Django 6.0.3 on 2026-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projectfeature_demo_url_projectfeature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='comap_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/'),
        ),
    ]
