# Generated by Django 6.0.3 on 2026-10-01 17:19

import django.db.models.deletion
import portfolio.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_experience_comap_logo_alter_projectimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='about',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='about',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('cv')),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='comap_logo',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('companies')),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('profile')),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('resume')),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in URLs. Example: ethiopnotify'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('projects/thumbnails')),
        ),
        migrations.AlterField(
            model_name='projectarchitecture',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('projects/architecture')),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('projects/features')),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.utils.OwnerUploadTo('projects/gallery')),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_category_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_category_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_project_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_skill_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_technology_slug_per_owner'),
        ),
    ]
