# Generated by Django 6.0.3 on 2026-10-01 20:07

import django.db.models.deletion
import portfolio.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_experience_comap_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-current', '-start_date']},
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Shown as evidence next to the skill.', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('issuer', models.CharField(help_text='e.g. Google, Coursera, ALX', max_length=220)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('credential_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('certificates'))),
                ('order', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='certificates', to='portfolio.skill')),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='e.g. Bahir Dar University', max_length=220)),
                ('level', models.CharField(choices=[('high_school', 'High school'), ('tvet', 'TVET'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's (BSc/BA)"), ('master', "Master's (MSc/MA)"), ('doctorate', 'Doctorate (PhD)'), ('other', 'Other')], default='bachelor', max_length=20)),
                ('field_of_study', models.CharField(blank=True, help_text='e.g. Computer Engineering', max_length=220)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, help_text='e.g. CGPA 3.8/4.0', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Thesis, final project, activities, honors')),
                ('order', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
