# Generated by Django 6.0.3 on 2026-10-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_copy_technologies_to_skills'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='technology',
            name='unique_technology_slug_per_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
