# Generated by Django 6.0.3 on 2026-10-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Backend developer, Solo full-stack', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('archived', 'Archived')], default='completed', max_length=20),
        ),
    ]
