# Generated by Django 6.0.3 on 2026-10-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_project_status_role_started_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-created_at']},
        ),
    ]
