# Generated by Django 6.0.3 on 2026-10-01 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_project_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional working proficiency'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], default='professional', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_language_per_owner')],
            },
        ),
    ]
