# Generated by Django 6.0.3 on 2026-10-02 18:43

import django.db.models.deletion
import portfolio.site_settings
import portfolio.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_portfolio_website_and_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='interests',
            field=models.TextField(blank=True, help_text='One per line. Shown as fun facts on the About page.'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='availability',
            field=models.CharField(blank=True, choices=[('open', 'Open to work'), ('freelance', 'Available for freelance'), ('busy', 'Busy'), ('unavailable', 'Not available')], max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='availability_note',
            field=models.CharField(blank=True, help_text='Shown next to the status, e.g. "Busy until March"', max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Calendly-style booking link'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currently_learning',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='settings',
            field=models.JSONField(blank=True, default=dict, validators=[portfolio.site_settings.validate_settings]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA name for the local-time card, e.g. Africa/Addis_Ababa', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. SaaS, API, Website. Used as a filter.', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='The problem the project solves.'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, help_text='What changed because of it. Add numbers as metrics.'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.utils.OwnerUploadTo('about'))),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.about')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='portfolio.about')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "+40%", "3x", "120ms"', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. CTO', max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=portfolio.utils.OwnerUploadTo('testimonials'))),
                ('url', models.URLField(blank=True, help_text='Link to the person, e.g. LinkedIn')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
