# Generated by Django 6.0.3 on 2026-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_design_system_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order', models.OrderBy(models.F('issue_date'), descending=True, nulls_last=True)]},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', models.OrderBy(models.F('start_date'), descending=True, nulls_last=True)], 'verbose_name_plural': 'Education'},
        ),
    ]
